swagger: "2.0"
info:
  version: "0.0.1"
  title: "REST API for AWS Lambda CRUD Operation"
  description: "Create/Update/Delete AWS Lambda Functions using REST API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Varun Joshi @vajoshi@iu.edu"
  license:
    name: "Apache"

basePath: "/lambda"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /deploy-pkg:
    post:
      tags:
      - Deploy Package (Zip File) For Lambda
      operationId: lambda.upload
      consumes:
      - multipart/form-data
      parameters:
      - name: pkg
        description: Browse Zip file deployment package for creating Lambda Function
        in: formData
        type: file
        required: True
      responses:
        "200":
          description: "Zip File Deployment Package To Upload"
          schema:
            $ref: "#/definitions/Lambda"

  /functions:
    get:
      tags:
        - Lambda
      operationId: lambda.list_aws_lambda
      description: "lists all available Lambda Functions (limit 50)"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Lambda Functions"
          schema:
            $ref: "#/definitions/Lambda"
  /function{fname}:
    get:
      tags:
      - Lambda
      operationId: lambda.get_aws_lambda_by_name
      produces:
      - "application/json"
      parameters:
      - name: fname
        in: path
        type: string
        required: True
      responses:
        "200":
          description: "Function name to search"
          schema:
            $ref: "#/definitions/Lambda"

    post:
      tags:
      - Lambda
      operationId: lambda.create_aws_lambda
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: fname
        description: Function name to create
        in: path
        type: string
        required: True
      - name: renv
        description: Runtime environment for AWS Lambda Function(Accepted Values - ['nodejs','nodejs4.3','nodejs6.10','nodejs8.10','java8','python2.7','python3.6','python3.7','dotnetcore1.0','dotnetcore2.0','dotnetcore2.1','nodejs4.3-edge','go1.x']
        in: query
        type: string
        required: True
      - name: pkg
        description: Zip file name of the deployment package for Lambda Function to create
        in: query
        type: string
        required: True
      - name: handler
        description: Lambda Function Handler
        in: query
        type: string
        required: True
      - name: func_name
        description: Python file name with Lambda function
        in: query
        type: string
        required: True

      responses:
        "200":
          description: "Function name to create"
          schema:
            $ref: "#/definitions/Lambda"

    delete:
        tags:
        - Lambda
        operationId: lambda.del_aws_lambda
        parameters:
        - name: fname
          in: path
          type: string
          required: True
        responses:
          "200":
            description: "Function name to delete"
            schema:
              $ref: "#/definitions/Lambda"
definitions:
  Lambda:
    type: "object"
    required:
      - "result"
    properties:
      result:
        type: "string"

