swagger: "2.0"
info:
  version: "0.0.1"
  title: "REST API for AWS Lambda CRUD Operation"
  description: "Create/Update/Delete AWS Lambda Functions using REST API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Varun Joshi @vajoshi@iu.edu"
  license:
    name: "Apache"

basePath: "/lambda"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /deploy-pkg:
    post:
      tags:
      - Deploy Package (Zip File) For Lambda
      operationId: lambda.upload
      summary: "Upload zip file containing AWS Lambda Handler"
      consumes:
      - multipart/form-data
      parameters:
      - name: pkg
        description: Browse Zip file deployment package for creating Lambda Function
        in: formData
        type: file
        required: True
      responses:
        "200":
          description: "Zip File Deployment Package To Upload"
          schema:
            $ref: "#/definitions/Lambda"

  /functions:
    get:
      tags:
        - Lambda
      operationId: lambda.list_aws_lambda
      summary: "Get name of all AWS Lambda Functions"
      description: "lists all available Lambda Functions (limit 50)"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Lambda Functions"
          schema:
            $ref: "#/definitions/Lambda"
  /function/{fname}:
    get:
      tags:
      - Lambda
      operationId: lambda.get_aws_lambda_by_name
      summary: "Get AWS Lambda function configuration by name"
      produces:
      - "application/json"
      parameters:
      - name: fname
        in: path
        type: string
        required: True
      responses:
        "200":
          description: "Function Search"
          schema:
            $ref: "#/definitions/Lambda"

    post:
      tags:
      - Lambda
      operationId: lambda.create_aws_lambda
      summary: "Create AWS Lambda Function"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: fname
        description: Name for the AWS Lambda Function which will be created
        in: path
        type: string
        required: True
      - name: fprop
        description: Required parameters to create AWS Lambda Function -Name of the file containing Lambda code (cfile),Runtime env (renv), AWS Lambda handler name (handler), zip file name of the AWS Lambda Deployment package(pkg)
        in: body
        schema:
          type: object
          required:
          - renv
          - handler
          - cfile
          - pkg
          properties:
            renv:
              type: string
              description: Runtime env for AWS Lambda Function
            handler:
              type: string
            cfile:
              type: string
            pkg:
              type: string
          example:
            renv: python3.7
            handler: lambda_handler
            cfile: hello.py
            pkg: hello.zip

      responses:
        "200":
          description: "Function Created"
          schema:
            $ref: "#/definitions/Lambda"

    delete:
        tags:
        - Lambda
        operationId: lambda.del_aws_lambda
        summary: "Delete AWS Lambda Function by name"
        parameters:
        - name: fname
          in: path
          type: string
          required: True
        responses:
          "200":
            description: "Function Deleted"
            schema:
              $ref: "#/definitions/Lambda"
definitions:
  Lambda:
    type: "object"
    required:
      - "result"
    properties:
      result:
        type: "string"

