swagger: "2.0"
info:
  version: "0.0.1"
  title: "Search Text using AWS Lambda Function"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Call Lambda for Data"
  license:
    name: "Apache"
host: "xxxxxx.compute.amazonaws.com:8080"
basePath: "/cloudmesh"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /search:
    get:
      tags:
        - SEARCH
      operationId: search.invoke_lambda
      produces:
        - "application/json"
      parameters:
        - name: text
          in: query
          type: string
          required: True
        - name: filename
          in: query
          type: string
          required: True
      responses:
        "200":
          description: "show search results"
          schema:
            $ref: "#/definitions/SEARCH"
definitions:
  SEARCH:
    type: "object"
    required:
      - "result"
    properties:
      result:
        type: "string"